name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4           # eve-backend
        with:
          repository: eve-esa/backend
          ref: staging
          path: backend
      - uses: actions/checkout@v4           # evalkit
        with:
          repository: eve-esa/evalkit
          ref: task-refactoring
          path: evalkit
      - uses: actions/checkout@v4           # data-scrapping
        with:
          repository: eve-esa/data-scraping
          ref: docs
          path: data-scraping
      - uses: actions/checkout@v4           # data-process
        with:
          repository: eve-esa/data-processing
          ref: main
          path: data-processing
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings-python
      - run: pip install mkdocs-multirepo-plugin
      - run: mkdocs gh-deploy --force